### ISSUE TITLE
Sprint 5: Sprint Checklist

### ISSUE THREAD

**Issue by Waldleufer** [amosproj/amos-ss2021-carbon-footprint#44]
## Software Product
- [x] Tagged
- [x] Testable
- [x] Deployable Software code base and product 

## Planning Documents
- [x] Clean [kanban board](https://github.com/amosproj/amos-ss2021-carbon-footprint/projects/1)
- [x] Completed weekly release planning
- [x] [Planning document](https://docs.google.com/spreadsheets/d/1riRj26jKjfG1dEwkKn4bxvcrr5PahKq9wyz4ao3RDgI/edit?usp=sharing) submitted

- [x] Added Additional information (if neccessary)

## Process Improvement
- [x] Impediments documented

- [x] [Happyness Index](https://happy-amos.appspot.com/Project?project=6723300591927296&course=5714692550950912) survey taken by all team members

**Comment by Waldleufer** [comment]
I remembered I created this issue template in the beginning, might as well use it ^^ 

@IremToroslu @olyaee you are this sprints release manager and scrum master / PO hence I "assigned" you to this. This issue will not show up on the kanban board.

**Comment by Waldleufer** [comment]
In this sprint we additionally have the following deliverables:

- [ ] [Mid-project release plan](https://docs.google.com/document/d/1GJhwCKf7U3sSZBQjNSu5z1JqssSQTw9Z_3PI4_88v1A/edit#heading=h.qxtmijxadkfk)
- [ ] [DoD for sprint releases](https://docs.google.com/document/d/1GJhwCKf7U3sSZBQjNSu5z1JqssSQTw9Z_3PI4_88v1A/edit#heading=h.98966wa07d0k)
- [ ] [DoD for product releases](https://docs.google.com/document/d/1GJhwCKf7U3sSZBQjNSu5z1JqssSQTw9Z_3PI4_88v1A/edit#heading=h.98966wa07d0k)

**Comment by Waldleufer** [comment]
https://github.com/dirkriehle/amos-course/blob/master/Generated/Lecture%20slides/AMOS%20D02%20-%20Planning%20and%20Tracking.pdf
