### ISSUE TITLE
Integrate data from SimaPro into the User Interface

### ISSUE THREAD

**Issue by MichaelScheiderer** [amosproj/amos-ss2021-carbon-footprint#46]
## User story
1. As a salesperson
2. I need to have an overview of the projects that are available on SimaPro
3. So that I can choose the one I want to present to my customer

## Acceptance criteria
* [x] The product grid-overview shows the products that are available on SimaPro
* [x] The basic backend Scaffolding has been done (#47)
* [x] The backend has a middleware that does the login to the SimaPro API (#48)
* [x] The backend controller can proxy various incoming requests (#49)

## Definition of done
* [x] Documentation for the feature is done
* [x] Feature branch has been merged
* [x] Code has been reviewed by at least one other team member
* [x] Unit tests are written

**Comment by Waldleufer** [comment]
The basic backend Scaffolding has been done

**Comment by Waldleufer** [comment]
The backend has a middleware that does the login to the SimaPro API

**Comment by Waldleufer** [comment]
The backend controller can proxy various incoming requests

**Comment by Waldleufer** [comment]
If there is only one model available on SimaPro, no drop-down window is shown

**Comment by Waldleufer** [comment]
![image](https://user-images.githubusercontent.com/22003632/120098452-572e9f00-c136-11eb-9029-bac1b6609e48.png)

🎉

**Comment by Waldleufer** [comment]
@olyaee  My question now:
Where should the scenarios go? Because they are now just within the same list of data, and we will have to do filtering stuff probably.

**Comment by MichaelScheiderer** [comment]
From the glossary:
Scenario: The scenario created by changing default values of a model.

So, if you press on a product/model then it first shows the baseline scenario. Then, when you change a variable it shows a different scenario. So the scenarios should be shown on the details page after selecting a different variable. Was this understandable? 😊

**Comment by Waldleufer** [comment]
Yes that is clear to me. Thanks!

Then the next question is: where in the SimaPro data is the information about the variable? Or do we just say `scenario 1` `scenario 2` for now in the variable Dropdown on the details page? Because as you can see in the screenshot above, the only difference is the _Scenario1, _Scenario2 for now.

**Comment by MichaelScheiderer** [comment]
Seems like those informations are still missing. I will clarify that together with the industry partner. They would need to provide this information via SimaPro. 
We have the same problem with the categories: "Which Projects belongs to which Category? e.g. Generation/Solutions". We talked to the SimaPro Experts, there is no way in SimaPro to tag or categorize the project. The only option will be to use the Project name or a comment field, which you also should be able to access via the API. The plan is to somehow encode this information in plain text in one of those field so its possible to automatically parse it.
For example something like: Categorie:Generation/Products#Name:"Gas Turbines"#Model:XYZ2#Location:Germany
So I guess the Information "which scenario changes which variable" will also be encoded in one of those fields in the future, but its not done yet. I try to find a solution as fast as possible but they didnt reply to my email yet.

For now I think there is no way to correctly connect the projects, except hardcoding them. So I think it would be best to leave it like this until we found the best solution.
