### ISSUE TITLE
Sprint 1: Sprint Checklist

### ISSUE THREAD

**Issue by Waldleufer** [amosproj/amos-ss2021-carbon-footprint#6]
## Planning Documents
- [x] Clean [kanban board](https://github.com/amosproj/amos-ss2021-carbon-footprint/projects/1)
- [x] Completed weekly release planning
- [x] [Planning document](https://docs.google.com/spreadsheets/d/1riRj26jKjfG1dEwkKn4bxvcrr5PahKq9wyz4ao3RDgI/edit?usp=sharing) submitted to [Deliverables](https://github.com/amosproj/amos-ss2021-carbon-footprint/tree/Deliverables-Sprint1/Deliverables)

- [x] Added Additional information (if neccessary)

## Process Improvement
- [x] Impediments documented

- [x] [Happyness Index](https://happy-amos.appspot.com/Project?project=6723300591927296&course=5714692550950912) survey taken by all team members
