### ISSUE TITLE
Sprint 7: Sprint Checklist

### ISSUE THREAD

**Issue by Waldleufer** [amosproj/amos-ss2021-carbon-footprint#77]
## Software Product
- [ ] Tagged
- [ ] Testable
- [ ] Deployable Software code base and product 

## Planning Documents
- [ ] Clean [kanban board](https://github.com/amosproj/amos-ss2021-carbon-footprint/projects/1)
- [ ] Completed weekly release planning
- [ ] [Planning document](https://docs.google.com/spreadsheets/d/1riRj26jKjfG1dEwkKn4bxvcrr5PahKq9wyz4ao3RDgI/edit?usp=sharing) submitted

- [ ] Added Additional information (if neccessary)

## Process Improvement
- [ ] Impediments documented

- [ ] [Happyness Index](https://happy-amos.appspot.com/Project?project=6723300591927296&course=5714692550950912) survey taken by all team members
