### ISSUE TITLE
Integrate data from SimaPro into the graphs

### ISSUE THREAD

**Issue by MichaelScheiderer** [amosproj/amos-ss2021-carbon-footprint#82]
## User story
1. As a salesperson
2. I need to visualize and show to my customers what was calculated in SimaPro
3. So that I can convince my customer to decide for a product which reduces CO2 impact

## Acceptance criteria
* [x] If there is only one model available on SimaPro, no drop-down window is shown (#74)
* [x] If there is more than one models available on SimaPro, the available models are shown in a drop-down window (#74)
* [x] After selecting a Model, the graphs are visualized based on the data received from the SimaPro API (#87)
   * [x] Sub task: Get the data from SimaPro.
   * [x] Sub task: Format the data to make it usable.
   * [x] Sub task: Create getter methods for each of the charts/tables (#85)
   * [x] Sub task: Make charts/table display the data from the getter methods (#86)

## Definition of done
* [ ] Documentation for the feature is done
* [ ] Feature branch has been merged
* [x] Code has been reviewed by at least one other team member
* [x] Unit tests are written

**Comment by Waldleufer** [comment]
@SaiVarunVaranasi @ScoutAtlas and @Waldleufer tried to make that work, but the data we get and the data we want to display seems incompatible. Crosspost from Slack:

**Comment by Waldleufer** [comment]
### We currently get a lot of data:
![image (3)](https://user-images.githubusercontent.com/22003632/121536566-79140580-ca03-11eb-8df8-60ad57c0f998.png)


### And the problem we are having is:
By using the function to get the data (https://amosproject8.slack.com/archives/C020MFC5AU8/p1623138797001700) we get a lot of data (60.000 lines of data Computation takes about 10s on the SimaPro Server) and still the data that is required to fill the tables, that we should use is missing.

- There is a huge discrepancy between the data we get and the data we want to display. There does not seem to be a uniform naming, so we can't reliably link the data each time.
- That means in particular that we don't have a way to get the Material Composition (We would have to search through all data and somehow determine what is a material and what not, since everything is in one big table)
- We can not get the data for the impact assessment: Materials, Manufactoring and Transport and operation, and we would have to guess for what data is required for the End of Life at this point.
- The data for the requested table is a very good example for our problem: (See second screenshot attached) also: We only can get the total values for these, so only column 1 in our table would be fillable with this data. 

![Screenshot 2021-06-10 153727](https://user-images.githubusercontent.com/22003632/121536785-a95ba400-ca03-11eb-8303-5ca72523e35c.png)

**Comment by MartinDuersch** [comment]
https://stackoverflow.com/questions/27192621/reactjs-async-rendering-of-components
how about this
